development:
  adapter: postgresql
  encoding: unicode
  database: artmap_development
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: artmap_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: artmap_test
  pool: 5